export const cards = [
  {
    id: 1,
    name: "A",
    image: "01-hiragana-a",
    text: "Et coucou",
    color: "#e05a5aff",
  },
  {
    id: 2,
    name: "I",
    image: "02-hiragana-i",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    color: "#e29055ff",
  },
  {
    id: 3,
    name: "U",
    image: "03-hiragana-u",
    text: "Lorem ipsum dolor sit.",
    color: "#d8b752ff",
  },
  {
    id: 4,
    name: "E",
    image: "04-hiragana-e",
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    color: "#9fb548ff",
  },
  {
    id: 5,
    name: "O",
    image: "05-hiragana-o",
    text: "Lorem, ipsum.",
    color: "#55d4e2ff",
  },
  {
    id: 6,
    name: "KA",
    image: "06-hiragana-ka",
    text: "Lorem ipsum dolor sit amet .",
    color: "#556ce2ff",
  },
  {
    id: 7,
    name: "KI",
    image: "07-hiragana-ki",
    text: "Lorem.",
    color: "#bf55e2ff",
  }, 
  {
    id: 8,
    name: "KU",
    image: "08-hiragana-ku",
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde?",
    color: "#7f55e2ff",
  },
  {
    id: 9,
    name: "KE",
    image: "09-hiragana-ke",
    text: "Lorem ipsum sit.",
    color: "#e25576ff",
  },
  {
    id: 10,
    name: "KO",
    image: "10-hiragana-ko",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, corrupti. Autem.",
    color: "#55e278ff",
  },
];
